vich_uploader:
    db_driver: orm
    mappings:
        repas_images:
            uri_prefix: /uploads/repas
            upload_destination: '%kernel.project_dir%/public/uploads/repas'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer 